
class BadArgumentError(Exception):
    """custom exception"""
    pass


class NotFoundError(Exception):
    """custom exception"""
    pass
